# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  branches:
    dev:
      - step:
          name: Test to deployment
          caches:
            - node
          script:
            - npm install
            - npm run build
      - step:
          name: Deploy to dev
          script:
            - ssh $DEV_USER@$DEV_ADDR "cd /projects/hubbco-dev/$BITBUCKET_REPO_SLUG && git pull && docker-compose stop && docker-compose rm -f && docker system prune -f && docker-compose build && docker-compose up -d && exit;"
    staging:
      - step:
          name: Test to deployment
          caches:
            - node
          script:
            - npm install
            - npm run build
      - step:
          name: Deploy to staging
          deployment: staging
          script:
            - ssh $STAGING_USER@$STAGING_ADDR "cd /projects/hubbco-stag/$BITBUCKET_REPO_SLUG && git pull && docker-compose stop && docker-compose rm -f && docker system prune -f && docker-compose build && docker-compose up -d && exit;"
    master:
      - step:
          name: Test to deployment
          caches:
            - node
          script:
            - npm install
            - npm run build
      - step:
          name: Deploy to production
          deployment: production
          trigger: manual
          script:
            - ssh $PRODUCTION_USER@$PRODUCTION_ADDR "cd /projects/hubbco/$BITBUCKET_REPO_SLUG && git pull && docker-compose stop && docker-compose rm -f && docker system prune -f && docker-compose build && docker-compose up -d && exit;"
