# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3-alpine

pipelines:
  branches:
    master:
      - step:
          name: Test to deployment
          deployment: test
          script:
            - npm install
            - npm run build
      - step:
          name: Deploy to staging
          deployment: staging
          script:
            - apk add --update openssh
            - ssh $STAG_USER@$STAG_ADDR "cd $STAG_PROJECT_PATH && git pull && docker system prune -f && docker-compose build && docker-compose up -d && exit;"
  custom: # Pipelines that are triggered manually
    production-deployment:
      - step:
          name: Test to deployment
          deployment: test
          script:
            - npm install
            - npm run build
      - step:
          deployment: production
          script:
            - apk add --update openssh
            - ssh $PROD_USER@$PROD_ADDR "cd $PROD_PROJECT_PATH && git pull && docker system prune -f && docker-compose build && docker-compose up -d && exit;"
