const NS_CATEGORY = 'CATEGORY';

export default{
    CATEGORY_LISTCATE:NS_CATEGORY + '/LISTCATE',
    CATEGORY_PAGINATION:NS_CATEGORY + '/PAGINATION',
    ALL_CATEGORY:NS_CATEGORY + '/ALL_CATEGORY',
};
