const NS_SUPPLIERS = 'SUPPLIERS';
export default{
    SUPPLIERS_LIST:NS_SUPPLIERS + '/SUPPLIERS_LIST',
    SUPPLIERS_PAGINATION:NS_SUPPLIERS + '/PRODUCTS_PAGINATION',
    SET_DELETE_SUPPLIERS:NS_SUPPLIERS + '/SET_DELETE_PRODUCT'
};