const NS_PRODUCT = 'PRODUCT';
export default{
    PRODUCT_BY_CATEGORIES:NS_PRODUCT + '/PRODUCT_BY_CATEGORIES',
    PRODUCTS_LIST:NS_PRODUCT + '/PRODUCTS_LIST',
    PRODUCTS_PAGINATION:NS_PRODUCT + '/PRODUCTS_PAGINATION',
    SET_DELETE_PRODUCT:NS_PRODUCT + '/SET_DELETE_PRODUCT'
};