const NS_BRANDS = 'BRANDS';
export default{
    BRAND_ID:NS_BRANDS + '/BRAND_ID',
    ALL_BRANDLIST:NS_BRANDS + '/ALL_BRANDLIST',
    BRAND_PAGINATION:NS_BRANDS + '/BRAND_PAGINATION',
    BRAND_BY_CATEGORIES:NS_BRANDS + '/BRAND_BY_CATEGORIES',
    ALL_BRANDS_OF_SUPPLIER:NS_BRANDS + '/ALL_BRANDS_OF_SUPPLIER',
    PRODUCT_BY_BRAND:NS_BRANDS + '/PRODUCT_BY_BRAND',
    BRAND_DELETED_ID:NS_BRANDS + '/BRAND_DELETED_ID'
};
