const NS_KEYWORDS = 'KEYWORDS';
export default{
    ALL_KEYWORDS:NS_KEYWORDS + '/ALL_KEYWORDS',
    KEYWORDS_PAGINATION:NS_KEYWORDS + '/KEYWORDS_PAGINATION',
    KEYWORD_DELETED_ID:NS_KEYWORDS + '/KEYWORD_DELETED_ID'
};
